### ISSUE TITLE
Test fails when localtime and gmtime differs

### ISSUE THREAD

**Issue by guimard** [sisimai/p5-Sisimai#288]
Hello,

it seems that Sisimai tests fail when localtime and gmtime don't give the same day. See this [build log](https://tests.reproducible-builds.org/debian/logs/buster/amd64/libsisimai-perl_4.22.7-1.build2.log.gz) _(Thu Aug  9 05:17:46 +14 2018)_

**Comment by azumakuniyuki** [comment]
Hello,

Thanks for the bug report. We are going to try tests on some hosts with other time zone (neither JST nor UTC).

Thanks

**Comment by guimard** [comment]
See also https://github.com/sisimai/p5-Sisimai/pull/289

**Comment by guimard** [comment]
It seems enough

**Comment by azumakuniyuki** [comment]
Thanks for the patch ! I've merged the Pull-Request just now.

**Comment by guimard** [comment]
You tested it ?

**Comment by azumakuniyuki** [comment]
Sure, I've tested on PDT :-)

**Comment by guimard** [comment]
Hello,
please reopen this issue: I still have the bug with my patch:
* https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/libsisimai-perl.html

**Comment by guimard** [comment]
Or do I need cccb4ef ?

**Comment by azumakuniyuki** [comment]
Hello,

commit cccb4ef1978e0a3cd8b76301494759b4e91f6eeb is a patch for UTC+14 timezone.
If you need, May I will set tag `v4.22.7p3` ?

**Comment by guimard** [comment]
@azumakuniyuki: hello, this is not highly important since tests work globally. I can wait for your next release

**Comment by guimard** [comment]
Hello @azumakuniyuki, uploaded to Debian/unstable (in testing on monday). Thanks !

NB: I'll look at Debian CI to verify that all is OK

**Comment by guimard** [comment]
@azumakuniyuki: according to [Debian reproducible builds](https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/libsisimai-perl.html), this issue seems fixed now.

Thanks !
